# Generated by Django 3.2.13 on 2022-06-22 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_customer_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avtar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
