# Generated by Django 3.2.13 on 2022-06-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220612_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'ELECTRONICS'), ('Grossery', 'GROSSERY'), ('Clothings', 'CLOTHINGS'), ('HomeAppliance', 'HOME APPLIANCE')], max_length=100, null=True),
        ),
    ]
