# Generated by Django 3.2.13 on 2022-06-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Out of stock', 'OUT OF STOCK'), ('Delivery', 'DELIVERY')], max_length=50, null=True),
        ),
    ]
